const countries = [
        {
                "name": "United States",
                "altSpellings": ["US", "USA", "United States of America"],
                "callingCodes": ["1"],
                "capital": "Washington D.C.",
                "currencies": ["USD", "USN", "USS"],
                "demonym": "American",
                "nativeName": "United States",
                "provinces": ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"],
                "region": "Americas",
                "subregion": "Northern America",
                "timezones": ["UTC−12:00", "UTC−11:00", "UTC−10:00", "UTC−09:00", "UTC−08:00", "UTC−07:00", "UTC−06:00", "UTC−05:00", "UTC−04:00", "UTC+10:00", "UTC+12:00"],
                "translations": { "de": "Vereinigte Staaten von Amerika", "es": "Estados Unidos", "fr": "États-Unis", "ja": "アメリカ合衆国", "it": "Stati Uniti D'America" },
                flag: "🇺🇸",
                languages: [{
                        value: "US:en:United States:English:14",
                        text: "United States / English"
                }]
        },
        {
                flag: "🇦🇫",
                languages: [
                        { value: "AF:ps:Afghanistan:Pashto:5297", text: "Afghanistan / Pashto - پښتو" },
                        { value: "AF:fa:Afghanistan:Persian:38", text: "Afghanistan / Persian - فارسی" }
                ]

        },
        {
                flag: "🇦🇱",
                languages: [
                        { value: "AL:sq:Albania:Albanian:39", text: "Albania / Albanian - Shqip" },
                        { value: "AL:en:Albania:English:828", text: "Albania / English" }
                ]

        },
        {
                lag: "🇩🇿",
                languages: [
                        { value: "DZ:fr:Algeria:French:40", text: "Algeria / French - Français" },
                        { flag: "🇩🇿", value: "DZ:ar:Algeria:Arabic:41", text: "Algeria / Arabic - العربية" },

                ]
        },
        { flag: "🌏", languages: [{ value: "AS:en:American Samoa:English:42", text: "American Samoa / English" }] },
        { flag: "🇦🇩", languages: [{ value: "AD:ca:Andorra:Catalan:43", text: "Andorra / Catalan - Català" }] },
        { flag: "🇦🇴", languages: [{ value: "AO:pt:Angola:Portuguese:45", text: "Angola / Portuguese (Portugal) - Português (Portugal)" }] },
        { flag: "🇦🇴", languages: [{ value: "AO:kg:Angola:Kongo:44", text: "Angola / Kongo" }] },
        { flag: "🇦🇮", languages: [{ value: "AI:en:Anguilla:English:46", text: "Anguilla / English" }] },
        { flag: "🇦🇬", languages: [{ value: "AG:en:Antigua and Barbuda:English:47", text: "Antigua and Barbuda / English" }] },
        {
                "name": "Argentina",
                "altSpellings": ["AR", "Argentine Republic", "República Argentina"],
                "callingCodes": ["54"],
                "capital": "Buenos Aires",
                "currencies": ["ARS"], "demonym": "Argentinean",
                "nativeName": "Argentina",
                "provinces": ["Antartica e Islas del Atlantico Sur", "Buenos Aires", "Buenos Aires Capital Federal", "Catamarca", "Chaco", "Chubut", "Cordoba", "Corrientes", "Entre Rios", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquen", "Rio Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucuman"],
                "region": "Americas",
                "subregion": "South America",
                "timezones": ["UTC−03:00"],
                "translations": { "de": "Argentinien", "es": "Argentina", "fr": "Argentine", "ja": "アルゼンチン", "it": "Argentina" },
                flag: "🇦🇷",

                languages: [{ value: "AR:es:Argentina:Espanol (Latinoamerica):48", text: "Argentina / Spanish (Latin America) - Español (Latinoamérica)" }]
        },
        {
                flag: "🇦🇲",
                languages: [
                        {  value: "AM:hy:Armenia:Armenian:49", text: "Armenia / Armenian - հայերեն" },
                        {  value: "AM:ru:Armenia:Russian:50", text: "Armenia / Russian - Русский" },

                ]
        },
        {
                flag: "🇦🇺",
                language: [
                        {  value: "AU:en:Australia:English:51", text: "Australia / English" }
                ]
        },
        { flag: "🇦🇹", languages:[{value: "AT:de:Austria:German:52", text: "Austria / German - Deutsch" }]},
        { flag: "🇦🇿", languages:[
                { flag: "🇦🇿", value: "AZ:ru:Azerbaijan:Russian ", text: "Azerbaijan / Russian - Русский" },
                {value: "AZ:az:Azerbaijan:Azerbaijan ", text: "Azerbaijan / Azerbaijan - azərbaycan" }]},
        { flag: "🇧🇸", languages:[{value: "BS:en:Bahamas:English", text: "Bahamas / English" }]},
        { flag: "🇧🇭", languages:[
                { flag: "🇧🇭", value: "BH:en:Bahrain:English", text: "Bahrain / English" },
                {value: "BH:ar:Bahrain:Arabic", text: "Bahrain / Arabic - العربية" }]},
        { flag: "🇧🇩", languages:[
                { flag: "🇧🇩", value: "BD:en:Bangladesh:English", text: "Bangladesh / English" },
                {value: "BD:bn:Bangladesh:Bengali ", text: "Bangladesh / Bengali - বাংলা" }]},
        { flag: "🇧🇾", languages:[
                { flag: "🇧🇾", value: "BY:ru:Belarus:Russian", text: "Belarus / Russian - Русский" },
                {value: "BY:be:Belarus:Belarusian ", text: "Belarus / Belarusian - беларуская" }]},
        { flag: "🇧🇪", languages:[
                { flag: "🇧🇪", value: "BE:fr:Belgium:French", text: "Belgium / French - Français" },
                { flag: "🇧🇪", value: "BE:de:Belgium:German", text: "Belgium / German - Deutsch" },
                { flag: "🇧🇪", value: "BE:en:Belgium:English", text: "Belgium / English" },
                {value: "BE:nl:Belgium:Dutch", text: "Belgium / Dutch - Nederlands" }]},
        { flag: "🇧🇿", languages:[
                { flag: "🇧🇿", value: "BZ:es:Belize:Spanish ", text: "Belize / Spanish (Latin America) - Español (Latinoamérica)" },
                {value: "BZ:en:Belize:English", text: "Belize / English" }]},
        { flag: "🇧🇯", languages:[
                { flag: "🇧🇯", value: "BJ:yo:Benin:Yoruba ", text: "Benin / Yoruba - Èdè Yorùbá" },
                {value: "BJ:fr:Benin:French", text: "Benin / French - Français" }]},
        { flag: "🇧🇹", languages:[{value: "BT:en:Bhutan:English", text: "Bhutan / English" }]},
        { flag: "🇧🇴", languages:[
                { flag: "🇧🇴", value: "BO:qu:Bolivia:Quechua:68", text: "Bolivia / Quechua - Runasimi" },
                {value: "BO:es:Bolivia:Espanol (Latinoamerica):67", text: "Bolivia / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇧🇦", languages:[
                { flag: "🇧🇦", value: "BA:sr:Bosnia and Herzegovina:Serbian", text: "Bosnia and Herzegovina / Serbian - Cрпски" },
                { flag: "🇧🇦", value: "BA:hr:Bosnia and Herzegovina:Croatian ", text: "Bosnia and Herzegovina / Croatian - Hrvatski" },
                {value: "BA:bs:Bosnia and Herzegovina:Bosnian ", text: "Bosnia and Herzegovina / Bosnian - bosanski" }]},
        { flag: "🇧🇼", languages:[
                { flag: "🇧🇼", value: "BW:en:Botswana:English", text: "Botswana / English" },
                {value: "BW:tn:Botswana:Tswana", text: "Botswana / Tswana" }]},
        { flag: "🇧🇷", languages:[{value: "BR:pt:Brazil:Portuguese (Brasil):73 ", text: "Brazil / Portuguese (Brazil) - Português (Brasil)" }]},
        { flag: "🇻🇬", languages:[{value: "VG:en:British Virgin Islands:English", text: "British Virgin Islands / English" }]},
        { flag: "🇧🇳", languages:[
                { flag: "🇧🇳", value: "BN:en:Brunei:English", text: "Brunei / English" },
                { flag: "🇧🇳", value: "BN:zh:Brunei:Chinese Simplified", text: "Brunei / Chinese Simplified (China) - 中文 简体" },
                {value: "BN:ms:Brunei:Malay ", text: "Brunei / Malay - Bahasa Melayu" }]},
        { flag: "🇧🇬", languages:[{value: "BG:bg:Bulgaria:Bulgarian", text: "Bulgaria / Bulgarian - Български" }]},
        { flag: "🇧🇫", languages:[{value: "BF:fr:Burkina Faso:French", text: "Burkina Faso / French - Français" }]},
        { flag: "🇧🇮", languages:[{value: "BI:fr:Burundi:French", text: "Burundi / French - Français" }]},
        { flag: "🇧🇮", value: "BI:sw:Burundi:Swahili", text: "Burundi / Swahili - Kiswahili" },
        { flag: "🇧🇮", value: "BI:rn:Burundi:Rundi", text: "Burundi / Rundi - Ikirundi" },
        { flag: "🇰🇭", languages:[{value: "KH:km:Cambodia:Khmer", text: "Cambodia / Khmer - ខ្មែរ" }]},
        { flag: "🇰🇭", value: "KH:en:Cambodia:English", text: "Cambodia / English" },
        { flag: "🇨🇲", languages:[{value: "CM:fr:Cameroon:French", text: "Cameroon / French - Français" }]},
        { flag: "🇨🇲", value: "CM:en:Cameroon:English", text: "Cameroon / English" },
        { flag: "🇨🇦", languages:[{value: "CA:en:Canada:English:23", text: "Canada / English" }]},
        { flag: "🇨🇦", value: "CA:fr:Canada:French:84", text: "Canada / French - Français" },
        { flag: "🇨🇻", languages:[{value: "CV:pt:Cape Verde:Portuguese", text: "Cape Verde / Portuguese (Portugal) - Português (Portugal)" }]},
        { flag: "🇨🇫", languages:[{value: "CF:fr:Central African Republic:French", text: "Central African Republic / French - Français" }]},
        { flag: "🇹🇩", languages:[{value: "TD:fr:Chad:French", text: "Chad / French - Français" }]},
        { flag: "🇹🇩", value: "TD:ar:Chad:Arabic", text: "Chad / Arabic - العربية" },
        { flag: "🇨🇱", languages:[{value: "CL:es:Chile:Espanol (Latinoamerica):89", text: "Chile / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇨🇴", languages:[{value: "CO:es:Colombia:Espanol (Latinoamerica):91", text: "Colombia / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇨🇩", languages:[{value: "CD:fr:Congo:French", text: "Congo - Kinshasa / French - Français" }]},
        { flag: "🇨🇩", value: "CD:sw:Congo:Swahili", text: "Congo - Kinshasa / Swahili - Kiswahili" },
        { flag: "🇨🇩", value: "CD:ln:Congo:Lingala", text: "Congo - Kinshasa / Lingala - Lingála" },
        { flag: "🇨🇩", value: "CD:ach:Congo:Acoli", text: "Congo - Kinshasa / Acoli" },
        { flag: "🇨🇩", value: "CD:lua:Congo:Ciluba", text: "Congo - Kinshasa / Ciluba - Luba-Lulua" },
        { flag: "🇨🇩", value: "CD:kg:Congo:kongo", text: "Congo - Kinshasa / Kongo" },
        { flag: "🇨🇰", languages:[{value: "CK:en:Cook Islands:English", text: "Cook Islands / English" }]},
        { flag: "🇨🇷", languages:[{value: "CR:es:Costa Rica:Espanol (Latinoamerica):102", text: "Costa Rica / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇨🇷", value: "CR:en:Costa Rica:English:3392", text: "Costa Rica / English" },
        { flag: "🇨🇮", languages:[{value: "CI:fr:Côte d’Ivoire:French ", text: "Côte d’Ivoire / French - Français" }]},
        { flag: "🇭🇷", languages:[{value: "HR:hr:Croatia:Croatian", text: "Croatia / Croatian - Hrvatski" }]},
        { flag: "🇨🇺", languages:[{value: "CU:es:Cuba:Espanol (Latinoamerica):105", text: "Cuba / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇨🇾", languages:[{value: "CY:en:Cyprus:English", text: "Cyprus / English" }]},
        { flag: "🇨🇾", value: "CY:el:Cyprus:Greek", text: "Cyprus / Greek - Ελληνικά" },
        { flag: "🇨🇾", value: "CY:tr:Cyprus:Turkish", text: "Cyprus / Turkish - Türkçe" },
        { flag: "🇨🇿", languages:[{value: "CZ:cs:Czechia:Czech", text: "Czechia / Czech - Čeština" }]},
        { flag: "🇩🇰", languages:[{value: "DK:da:Denmark:Danish", text: "Denmark / Danish - Dansk" }]},
        { flag: "🇩🇰", value: "DK:fo:Denmark:Faroese", text: "Denmark / Faroese - Føroyskt" },
        { flag: "🇩🇯", languages:[{value: "DJ:fr:Djibouti:French", text: "Djibouti / French - Français" }]},
        { flag: "🇩🇯", value: "DJ:ar:Djibouti:Arabic", text: "Djibouti / Arabic - العربية" },
        { flag: "🇩🇯", value: "DJ:so:Djibouti:Somali", text: "Djibouti / Somali - Soomaali" },
        { flag: "🇩🇲", languages:[{value: "DM:en:Dominica:English", text: "Dominica / English" }]},
        { flag: "🇩🇴", value: "DO:es:Dominican Republic:Espanol (Latinoamerica):116", text: "Dominican Republic / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇪🇨", languages:[{value: "EC:es:Ecuador:Espanol (Latinoamerica):117", text: "Ecuador / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇪🇬", languages:[{value: "EG:ar:Egypt:Arabic", text: "Egypt / Arabic - العربية" }]},
        { flag: "🇪🇬", value: "EG:en:Egypt:English", text: "Egypt / English" },
        { flag: "🇸🇻", languages:[{value: "SV:es:El Salvador:Espanol (Latinoamerica):119", text: "El Salvador / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇪🇪", languages:[{value: "EE:et:Estonia:Estonian", text: "Estonia / Estonian - Eesti" }]},
        { flag: "🇪🇪", value: "EE:ru:Estonia:Russian", text: "Estonia / Russian - Русский" },
        { flag: "🇪🇹", languages:[{value: "ET:am:Ethiopia:Amharic", text: "Ethiopia / Amharic - አማርኛ" }]},
        { flag: "🇪🇹", value: "ET:en:Ethiopia:English", text: "Ethiopia / English" },
        { flag: "🇪🇹", value: "ET:ti:Ethiopia:Tigrinya", text: "Ethiopia / Tigrinya - ትግርኛ" },
        { flag: "🇪🇹", value: "ET:so:Ethiopia:Somali", text: "Ethiopia / Somali - Soomaali" },
        { flag: "🇪🇹", value: "ET:om:Ethiopia:Oromo", text: "Ethiopia / Oromo - Oromoo" },
        { flag: "🇫🇯", languages:[{value: "FJ:en:Fiji:English", text: "Fiji / English" }]},
        { flag: "🇫🇮", languages:[{value: "FI:fi:Finland:Finnish", text: "Finland / Finnish - Suomi" }]},
        { flag: "🇫🇮", value: "FI:sv:Finland:Swedish", text: "Finland / Swedish - Svenska" },
        { flag: "🇫🇷", languages:[{value: "FR:fr:France:French:129", text: "France / French - Français" }]},
        { flag: "🇬🇦", languages:[{value: "GA:fr:Gabon:French", text: "Gabon / French - Français" }]},
        { flag: "🇬🇲", languages:[{value: "GM:wo:Gambia:Wolof", text: "Gambia / Wolof" }]},
        { flag: "🇬🇲", value: "GM:en:Gambia:English", text: "Gambia / English" },
        { flag: "🇬🇪", languages:[{value: "GE:ka:Georgia:Georgian", text: "Georgia / Georgian - ქართული" }]},
        { flag: "🇬🇪", value: "GE:en:Georgia:English", text: "Georgia / English" },
        { flag: "🇩🇪", languages:[{value: "DE:de:Germany:German:25", text: "Germany / German - Deutsch" }]},
        { flag: "🇬🇭", languages:[{value: "GH:en:Ghana:English", text: "Ghana / English" }]},
        { flag: "🇬🇭", value: "GH:ha:Ghana:Hausa", text: "Ghana / Hausa" },
        { flag: "🇬🇭", value: "GH:ak:Ghana:Akan", text: "Ghana / Akan" },
        { flag: "🇬🇭", value: "GH:ee:Ghana:Ewe", text: "Ghana / Ewe - Eʋegbe" },
        { flag: "🇬🇭", value: "GH:gaa:Ghana:Ga", text: "Ghana / Ga - Gã" },
        { flag: "🇬🇮", languages:[{value: "GI:en:Gibraltar:English", text: "Gibraltar / English" }]},
        { flag: "🇬🇮", value: "GI:es:Gibraltar:Spanish", text: "Gibraltar / Spanish - Español" },
        { flag: "🇬🇮", value: "GI:it:Gibraltar:Italian", text: "Gibraltar / Italian - Italiano" },
        { flag: "🇬🇮", value: "GI:pt:Gibraltar:Portuguese", text: "Gibraltar / Portuguese (Portugal) - Português (Portugal)" },
        { flag: "🇬🇷", languages:[{value: "GR:el:Greece:Greek", text: "Greece / Greek - Ελληνικά" }]},
        { flag: "🇬🇱", languages:[{value: "GL:da:Greenland:Danish", text: "Greenland / Danish - Dansk" }]},
        { flag: "🇬🇱", value: "GL:en:Greenland:English", text: "Greenland / English" },
        { flag: "🇬🇵", languages:[{value: "GP:fr:Guadeloupe:French", text: "Guadeloupe / French - Français" }]},
        { flag: "🇬🇹", languages:[{value: "GT:es:Guatemala:Spanish", text: "Guatemala / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇬🇬", languages:[{value: "GG:en:Guernsey:English", text: "Guernsey / English" }]},
        { flag: "🇬🇬", value: "GG:fr:Guernsey:French", text: "Guernsey / French - Français" },
        { flag: "🇬🇾", languages:[{value: "GY:en:Guyana:English", text: "Guyana / English" }]},
        { flag: "🇭🇹", languages:[{value: "HT:fr:Haiti:French", text: "Haiti / French - Français" }]},
        { flag: "🇭🇹", value: "HT:ht:Haiti:Haitian Creole", text: "Haiti / Haitian Creole - Kreyòl Ayisyen" },
        { flag: "🇭🇹", value: "HT:en:Haiti:English", text: "Haiti / English" },
        { flag: "🇭🇳", languages:[{value: "HN:es:Honduras:Espanol (Latinoamerica):153", text: "Honduras / Spanish (Latin America) - Español (Latinoamérica)" }]},
        { flag: "🇭🇰", languages:[{value: "HK:zh:Hong Kong:Chinese Traditional", text: "Hong Kong / Chinese Traditional (Hong Kong) - 中文 繁體" }]},
        { flag: "🇨🇳", value: "HK:zh:Hong Kong:Chinese Simplified", text: "Hong Kong / Chinese Simplified (China) - 中文 简体" },
        { flag: "🇭🇰", value: "HK:en:Hong Kong:English", text: "Hong Kong / English" },
        { flag: "🇭🇺", languages:[{value: "HU:hu:Hungary:Hungarian", text: "Hungary / Hungarian - Magyar" }]},
        { flag: "🇮🇸", languages:[{value: "IS:is:Iceland:Icelandic", text: "Iceland / Icelandic - Íslenska" }]},
        { flag: "🇮🇸", value: "IS:en:Iceland:English", text: "Iceland / English" },
        { flag: "🇮🇳", languages:[{value: "IN:en:India:English", text: "India / English" }]},
        { flag: "🇮🇷", value: "IN:hi:India:Hindi", text: "India / Hindi - हिंदी" },
        { flag: "🇮🇳", value: "IN:bn:India:Bengali", text: "India / Bengali - বাংলা" },
        { flag: "🇮🇷", value: "IN:te:India:Telugu", text: "India / Telugu - తెలుగు" },
        { flag: "🇮🇳", value: "IN:mr:India:Marathi", text: "India / Marathi - मराठी" },
        { flag: "🇮🇷", value: "IN:ta:India:Tamil", text: "India / Tamil - தமிழ்" },
        { flag: "🇮🇳", value: "IN:gu:India:Gujarati", text: "India / Gujarati - ગુજરાતી" },
        { flag: "🇮🇷", value: "IN:kn:India:Kannada", text: "India / Kannada - ಕನ್ನಡ" },
        { flag: "🇮🇳", value: "IN:ml:India:Malayalam", text: "India / Malayalam - മലയാളം" },
        { flag: "🇮🇷", value: "IN:pa:India:Punjabi", text: "India / Punjabi - ਪੰਜਾਬੀ" },
        { flag: "🇮🇩", languages:[{value: "ID:id:Indonesia:Indonesian", text: "Indonesia / Indonesian - Bahasa Indonesia" }]},
        { flag: "🇮🇩", value: "ID:en:Indonesia:English", text: "Indonesia / English" },
        { flag: "🇮🇩", value: "ID:jw:Indonesia:Javanese", text: "Indonesia / Javanese - Båså Jåwå" },
        { flag: "🇮🇩", value: "ID:ban:Indonesia:Balinese", text: "Indonesia / Balinese - Båså Bali" },
        { flag: "🇮🇶", languages:[{value: "IQ:ar:Iraq:Arabic", text: "Iraq / Arabic - العربية" }]},
        { flag: "🇮🇶", value: "IQ:en:Iraq:English", text: "Iraq / English" },
        { flag: "🇮🇶", value: "IQ:ckb:Iraq:Central Kurdish", text: "Iraq / Central Kurdish - کوردی" },
        { flag: "🇮🇪", languages:[{value: "IE:en:Ireland:English", text: "Ireland / English" }]},
        { flag: "🇮🇪", value: "IE:ga:Ireland:Irish ", text: "Ireland / Irish - Gaeilge" },
        { flag: "🇮🇱", languages:[{value: "IL:iw:Israel:Hebrew", text: "Israel / Hebrew - עברית" }]},
        { flag: "🇮🇱", value: "IL:ar:Israel:Arabic", text: "Israel / Arabic - العربية" },
        { flag: "🇮🇱", value: "IL:en:Israel:English", text: "Israel / English" },
        { flag: "🇮🇹", languages:[{value: "IT:it:Italy:Italian", text: "Italy / Italian - Italiano" }]},
        { flag: "🇮🇲", languages:[{value: "IM:en:Isle of Man:English", text: "Isle of Man / English" }]},
        { flag: "🇯🇵", languages:[{value: "JP:ja:Japan:Japanese", text: "Japan / Japanese - 日本語" }]},
        { flag: "🇯🇲", languages:[{value: "JM:en:Jamaica:English", text: "Jamaica / English" }]},
        { flag: "🇯🇪", languages:[{value: "JE:en:Jersey:English", text: "Jersey / English" }]},
        { flag: "🇯🇪", value: "JE:fr:Jersey:French", text: "Jersey / French - Français" },
        { flag: "🇯🇴", languages:[{value: "JO:ar:Jordan:Arabic", text: "Jordan / Arabic - العربية" }]},
        { flag: "🇯🇴", value: "JO:en:Jordan:English", text: "Jordan / English" },
        { flag: "🇰🇿", languages:[{value: "KZ:ru:Kazakhstan:Russian", text: "Kazakhstan / Russian - Русский" }]},
        { flag: "🇰🇿", value: "KZ:kk:Kazakhstan:Kazakh", text: "Kazakhstan / Kazakh - қазақ тілі" },
        { flag: "🇰🇪", languages:[{value: "KE:sw:Kenya:Swahili", text: "Kenya / Swahili - Kiswahili" }]},
        { flag: "🇰🇪", value: "KE:en:Kenya:English", text: "Kenya / English" },
        { flag: "🇰🇮", languages:[{value: "KI:en:Kiribati:English", text: "Kiribati / English" }]},
        { flag: "🇰🇼", value: "KW:ar:Kuwait:Arabic", text: "Kuwait / Arabic - العربية" },
        { flag: "🇰🇼", value: "KW:en:Kuwait:English", text: "Kuwait / English" },
        { flag: "🇰🇬", value: "KG:ky:Kyrgyzstan:Kyrgyz", text: "Kyrgyzstan / Kyrgyz - кыргызча" },
        { flag: "🇰🇬", value: "KG:ru:Kyrgyzstan:Russian", text: "Kyrgyzstan / Russian - Русский" },
        { flag: "🇱🇦", value: "LA:lo:Laos:Lao", text: "Laos / Lao - ລາວ" },
        { flag: "🇱🇦", value: "LA:en:Laos:English", text: "Laos / English" },
        { flag: "🇱🇻", value: "LV:lt:Latvia:Lithuanian", text: "Latvia / Lithuanian - Lietuvių" },
        { flag: "🇱🇻", value: "LV:lv:Latvia:Latvian", text: "Latvia / Latvian - Latviešu" },
        { flag: "🇱🇻", value: "LV:ru:Latvia:Russian", text: "Latvia / Russian - Русский" },
        { flag: "🇱🇧", value: "LB:ar:Lebanon:ArabiXc", text: "Lebanon / Arabic - العربية" },
        { flag: "🇱🇧", value: "LB:en:Lebanon:English", text: "Lebanon / English" },
        { flag: "🇱🇧", value: "LB:fr:Lebanon:French", text: "Lebanon / French - Français" },
        { flag: "🇱🇧", value: "LB:hy:Lebanon:Armenian", text: "Lebanon / Armenian - հայերեն" },
        { flag: "🇱🇸", value: "LS:en:Lesotho:English", text: "Lesotho / English" },
        { flag: "🇱🇸", value: "LS:st:Lesotho:Sotho", text: "Lesotho / Sotho - Southern Sotho" },
        { flag: "🇱🇾", value: "LY:it:Libya:Italian", text: "Libya / Italian - Italiano" },
        { flag: "🇱🇾", value: "LY:en:Libya:English", text: "Libya / English" },
        { flag: "🇱🇾", value: "LY:ar:Libya:Arabic", text: "Libya / Arabic - العربية" },
        { flag: "🇱🇮", value: "LI:de:Liechtenstein:German", text: "Liechtenstein / German - Deutsch" },
        { flag: "🇱🇹", value: "LT:lt:Lithuania:Lithuanian", text: "Lithuania / Lithuanian - Lietuvių" },
        { flag: "🇱🇺", value: "LU:de:Luxembourg:German", text: "Luxembourg / German - Deutsch" },
        { flag: "🇱🇺", value: "LU:fr:Luxembourg:French", text: "Luxembourg / French - Français" },
        { flag: "🇲🇰", value: "MK:mk:Macedonia:Macedonian", text: "Macedonia (FYROM) / Macedonian - македонски" },
        { flag: "🇲🇬", value: "MG:fr:Madagascar:French", text: "Madagascar / French - Français" },
        { flag: "🇲🇬", value: "MG:mg:Madagascar:Malagasy", text: "Madagascar / Malagasy" },
        { flag: "🇲🇼", value: "MW:ny:Malawi:Chewa", text: "Malawi / Chewa - Nyanja" },
        { flag: "🇲🇼", value: "MW:en:Malawi:English", text: "Malawi / English" },
        { flag: "🇲🇼", value: "MW:tum:Malawi:Tumbuka", text: "Malawi / Tumbuka" },
        { flag: "🇲🇾", value: "MY:en:Malaysia:English", text: "Malaysia / English" },
        { flag: "🇲🇾", value: "MY:ms:Malaysia:Malay", text: "Malaysia / Malay - Bahasa Melayu" },
        { flag: "🇲🇻", value: "MV:en:Maldives:English", text: "Maldives / English" },
        { flag: "🇲🇱", value: "ML:fr:Mali:French", text: "Mali / French - Français" },
        { flag: "🇲🇹", value: "MT:mt:Malta:Maltese", text: "Malta / Maltese - Malti" },
        { flag: "🇲🇹", value: "MT:en:Malta:English", text: "Malta / English" },
        { flag: "🇲🇷", value: "MU:en:Mauritius:English", text: "Mauritius / English" },
        { flag: "🇲🇷", value: "MU:fr:Mauritius:French", text: "Mauritius / French - Français" },
        { flag: "🇲🇷", value: "MU:mfe:Mauritius:Mauritian Creole", text: "Mauritius / Mauritian Creole - Kreol Morisien" },
        { flag: "🇲🇽", value: "MX:es:Mexico:Espanol (Latinoamerica):217", text: "Mexico / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇫🇲", value: "FM:en:Micronesia:English", text: "Micronesia / English" },
        { flag: "🇲🇩", value: "MD:ro:MVoldova:Romanian", text: "Moldova / Romanian - Română" },
        { flag: "🇲🇩", value: "MD:ru:Moldova:Russian", text: "Moldova / Russian - Русский" },
        { flag: "🇲🇳", value: "MN:mn:Mongolia:Mongolian", text: "Mongolia / Mongolian - монгол" },
        { flag: "🇲🇪", value: "ME:sr:Montenegro:Serbian", text: "Montenegro / Serbian - Cрпски" },
        { flag: "🇲🇪", value: "ME:bs:Montenegro:Serbian", text: "Montenegro / Serbian - bosanski" },
        { flag: "🇲🇸", value: "MS:en:Montserrat:English", text: "Montserrat / English" },
        { flag: "🇲🇦", value: "MA:fr:Morocco:French", text: "Morocco / French - Français" },
        { flag: "🇲🇿", value: "MZ:pt:Mozambique:Portuguese", text: "Mozambique / Portuguese (Portugal) - Português (Portugal)" },
        { flag: "🇲🇿", value: "MZ:sw:Mozambique:Swahili", text: "Mozambique / Swahili - Kiswahili" },
        { flag: "🇲🇿", value: "MZ:ny:Mozambique:Chewa", text: "Mozambique / Chewa - Nyanja" },
        { flag: "🇲🇿", value: "MZ:sn:Mozambique:Shona", text: "Mozambique / Shona - chiShona" },
        { flag: "🇲🇲", value: "MM:my:Myanmar:Burmese", text: "Myanmar (Burma) / Burmese - မြန်မာ" },
        { flag: "🇲🇲", value: "MM:en:Myanmar:English", text: "Myanmar (Burma) / English" },
        { flag: "🇳🇦", value: "NA:en:Namibia:English", text: "Namibia / English" },
        { flag: "🇳🇦", value: "NA:af:Namibia:Afrikaans", text: "Namibia / Afrikaans" },
        { flag: "🇳🇦", value: "NA:de:Namibia:German", text: "Namibia / German - Deutsch" },
        { flag: "🇳🇷", value: "NR:en:Nauru:English", text: "Nauru / English" },
        { flag: "🇳🇵", value: "NP:ne:Nepal:Nepali", text: "Nepal / Nepali - नेपाली" },
        { flag: "🇳🇵", value: "NP:en:Nepal:English", text: "Nepal / English" },
        { flag: "🇳🇱", value: "NL:nl:Netherlands:Dutch", text: "Netherlands / Dutch - Nederlands" },
        { flag: "🇳🇱", value: "NL:fy:Netherlands:West Frisian", text: "Netherlands / West Frisian - West Frysk" },
        { flag: "🇳🇿", value: "NZ:en:New Zealand:English", text: "New Zealand / English" },
        { flag: "🇳🇿", value: "NZ:mi:New Zealand:Maori", text: "New Zealand / Maori - Māori" },
        { flag: "🇳🇮", value: "NI:es:Nicaragua:Spanish", text: "Nicaragua / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇳🇮", value: "NI:en:Nicaragua:English", text: "Nicaragua / English" },
        { flag: "🇳🇪", value: "NE:fr:Niger:French", text: "Niger / French - Français" },
        { flag: "🇳🇪", value: "NE:ha:Niger:Hausa", text: "Niger / Hausa" },
        { flag: "🇳🇬", value: "NG:en:Nigeria:English", text: "Nigeria / English" },
        { flag: "🇳🇬", value: "NG:ig:Nigeria:Igbo", text: "Nigeria / Igbo - Asụsụ Igbo" },
        { flag: "🇳🇬", value: "NG:yo:Nigeria:Yoruba", text: "Nigeria / Yoruba - Èdè Yorùbá" },
        { flag: "🇳🇬", value: "NG:pcm:Nigeria:Nigerian Pidgin", text: "Nigeria / Nigerian Pidgin" },
        { flag: "🇳🇬", value: "NG:ha:Nigeria:Hausa", text: "Nigeria / Hausa" },
        { flag: "🇳🇺", value: "NU:en:Niue:English", text: "Niue / English" },
        { flag: "🇳🇫", value: "NF:en:Norfolk Island:English", text: "Norfolk Island / English" },
        { flag: "🇳🇴", value: "NO:no:Norway:Norwegian", text: "Norway / Norwegian - Norsk" },
        { flag: "🇴🇲", value: "OM:ar:Oman:Arabic", text: "Oman / Arabic - العربية" },
        { flag: "🇴🇲", value: "OM:en:Oman:English", text: "Oman / English" },
        { flag: "🇵🇰", value: "PK:en:Pakistan:English", text: "Pakistan / English" },
        { flag: "🇵🇰", value: "PK:ur:Pakistan:Urdu", text: "Pakistan / Urdu - اردو" },
        { flag: "🇵🇰", value: "PK:ps:Pakistan:Pashto", text: "Pakistan / Pashto - پښتو" },
        { flag: "🇵🇰", value: "PK:sd:Pakistan:Sindhi", text: "Pakistan / Sindhi" },
        { flag: "🇵🇸", value: "PS:ar:Palestine:Arabic", text: "Palestine / Arabic - العربية" },
        { flag: "🇵🇸", value: "PS:en:Palestine:English", text: "Palestine / English" },
        { flag: "🇵🇦", value: "PA:es:Panama:Espanol (Latinoamerica):257", text: "Panama / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇵🇦", value: "PA:en:Panama:English:5309", text: "Panama / English" },
        { flag: "🇵🇬", value: "PG:en:Papua New Guinea:English", text: "Papua New Guinea / English" },
        { flag: "🇵🇾", value: "PY:es:Paraguay:Espanol (Latinoamerica):258", text: "Paraguay / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇵🇪", value: "PE:es:Peru:Espanol (Latinoamerica):259", text: "Peru / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇵🇪", value: "PE:qu:Peru:Quechua:260", text: "Peru / Quechua - Runasimi" },
        { flag: "🇵🇭", value: "PH:tl:Philippines:Filipino", text: "Philippines / Filipino - Tagalog" },
        { flag: "🇵🇭", value: "PH:en:Philippines:English", text: "Philippines / English" },
        { flag: "🇵🇭", value: "PH:ceb:Philippines:Cebuano", text: "Philippines / Cebuano" },
        { flag: "🇵🇳", value: "PN:en:Pitcairn Islands:English", text: "Pitcairn Islands / English" },
        { flag: "🇵🇱", value: "PL:pl:Poland:Polish", text: "Poland / Polish - Polski" },
        { flag: "🇵🇹", value: "PT:pt:Portugal:Portuguese", text: "Portugal / Portuguese (Portugal) - Português (Portugal)" },
        { flag: "🇵🇷", value: "PR:es:Puerto Rico:Espanol (Latinoamerica)", text: "Puerto Rico / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇵🇷", value: "PR:en:Puerto Rico:English", text: "Puerto Rico / English" },
        { flag: "🇶🇦", value: "QA:ar:Qatar:Arabic", text: "Qatar / Arabic - العربية" },
        { flag: "🇶🇦", value: "QA:en:Qatar:English", text: "Qatar / English" },
        { flag: "🇷🇴", value: "RO:ro:Romania:Romanian", text: "Romania / Romanian - Română" },
        { flag: "🇷🇴", value: "RO:de:Romania:German", text: "Romania / German - Deutsch" },
        { flag: "🇷🇴", value: "RO:hu:Romania:Hungarian", text: "Romania / Hungarian - Magyar" },
        { flag: "🇷🇺", value: "RU:ru:Russia:Russian", text: "Russia / Russian - Русский" },
        { flag: "🇷🇼", value: "RW:en:Rwanda:English", text: "Rwanda / English" },
        { flag: "🇷🇼", value: "RW:sw:Rwanda:Swahili", text: "Rwanda / Swahili - Kiswahili" },
        { flag: "🇷🇼", value: "RW:fr:Rwanda:French", text: "Rwanda / French - Français" },
        { flag: "🇷🇼", value: "RW:rw:Rwanda:Rwanda", text: "Rwanda / Rwanda - Ikinyarwanda" },
        { flag: "🇼🇸", value: "WS:en:Samoa:English", text: "Samoa / English" },
        { flag: "🇸🇲", value: "SM:it:San Marino:Italian", text: "San Marino / Italian - Italiano" },
        { flag: "🇸🇹", value: "ST:pt:São Tomé &amp; Príncipe:Portuguese", text: "São Tomé &amp; Príncipe / Portuguese (Portugal) - Português (Portugal)" },
        { flag: "🇸🇦", value: "SA:ar:Saudi Arabia:Arabic", text: "Saudi Arabia / Arabic - العربية" },
        { flag: "🇸🇦", value: "SA:en:Saudi Arabia:English", text: "Saudi Arabia / English" },
        { flag: "🇸🇳", value: "SN:fr:Senegal:French", text: "Senegal / French - Français" },
        { flag: "🇸🇳", value: "SN:wo:Senegal:Wolof", text: "Senegal / Wolof" },
        { flag: "🇷🇸", value: "RS:sr:Serbia:Serbian Latin", text: "Serbia / Serbian Latin - Srpski Latinica" },
        { flag: "🇷🇸", value: "RS:sr:Serbia:Serbian", text: "Serbia / Serbian - Cрпски" },
        { flag: "🇸🇨", value: "SC:crs:Seychelles:Seychellois Creole", text: "Seychelles / Seychellois Creole" },
        { flag: "🇸🇨", value: "SC:fr:Seychelles:French", text: "Seychelles / French - Français" },
        { flag: "🇸🇨", value: "SC:en:Seychelles:English", text: "Seychelles / English" },
        { flag: "🇸🇱", value: "SL:en:Sierra Leone:English", text: "Sierra Leone / English" },
        { flag: "🇸🇱", value: "SL:kri:Sierra Leone:Krio", text: "Sierra Leone / Krio - Sierra Leone" },
        { flag: "🇸🇬", value: "SG:zh:Singapore:Chinese Simplified", text: "Singapore / Chinese Simplified (China) - 中文 简体" },
        { flag: "🇸🇬", value: "SG:ta:Singapore:Tamil", text: "Singapore / Tamil - தமிழ்" },
        { flag: "🇸🇬", value: "SG:en:Singapore:English", text: "Singapore / English" },
        { flag: "🇸🇬", value: "SG:ms:Singapore:Malay", text: "Singapore / Malay - Bahasa Melayu" },
        { flag: "🇸🇰", value: "SK:sk:Slovakia:Slovak", text: "Slovakia / Slovak - Slovenčina" },
        { flag: "🇸🇮", value: "SI:sl:Slovenia:Slovenian", text: "Slovenia / Slovenian - Slovenščina" },
        { flag: "🇸🇧", value: "SB:en:Solomon Islands:English", text: "Solomon Islands / English" },
        { flag: "🇸🇴", value: "SO:so:Somalia:Somali", text: "Somalia / Somali - Soomaali" },
        { flag: "🇸🇴", value: "SO:en:Somalia:English", text: "Somalia / English" },
        { flag: "🇸🇴", value: "SO:ar:Somalia:Arabic", text: "Somalia / Arabic - العربية" },
        { flag: "🇿🇦", value: "ZA:af:South Africa:Afrikaans", text: "South Africa / Afrikaans" },
        { flag: "🇿🇦", value: "ZA:zu:South Africa:Zulu", text: "South Africa / Zulu - isiZulu" },
        { flag: "🇿🇦", value: "ZA:tn:South Africa:Tswana", text: "South Africa / Tswana" },
        { flag: "🇿🇦", value: "ZA:en:South Africa:English", text: "South Africa / English" },
        { flag: "🇿🇦", value: "ZA:st:South Africa:Sotho", text: "South Africa / Sotho - Southern Sotho" },
        { flag: "🇿🇦", value: "ZA:xh:South Africa:Xhosa", text: "South Africa / Xhosa - isiXhosa" },
        { flag: "🇿🇦", value: "ZA:nso:South Africa:Northern Sotho", text: "South Africa / Northern Sotho - Sepedi" },
        { flag: "🇰🇷", value: "KR:ko:South Korea:Korean", text: "South Korea / Korean - 한국어" },
        { flag: "🇪🇸", value: "ES:es:Spain:Spanish:26", text: "Spain / Spanish - Español" },
        { flag: "🇪🇸", value: "ES:gl:Spain:Galician:306", text: "Spain / Galician - Galego" },
        { flag: "🇪🇸", value: "ES:ca:Spain:Catalan:309", text: "Spain / Catalan - Català" },
        { flag: "🇪🇸", value: "ES:eu:Spain:Basque:307", text: "Spain / Basque - Euskara" },
        { flag: "🇱🇰", value: "LK:si:Sri LanXka:Sinhalese", text: "Sri Lanka / Sinhalese - සිංහල" },
        { flag: "🇱🇰", value: "LK:en:Sri Lanka:English", text: "Sri Lanka / English" },
        { flag: "🇱🇰", value: "LK:ta:Sri Lanka:Tamil", text: "Sri Lanka / Tamil - தமிழ்" },
        { flag: "🇸🇭", value: "SH:en:St. Helena:English", text: "St. Helena / English" },
        { flag: "🇻🇨", value: "VC:en:St. Vincent &amp; Grenadines:English", text: "St. Vincent &amp; Grenadines / English" },
        { flag: "🇸🇷", value: "SR:nl:Suriname:Dutch - Nederlands", text: "Suriname / Dutch - Nederlands" },
        { flag: "🇸🇷", value: "SR:en:Suriname:English", text: "Suriname / English" },
        { flag: "🇸🇪", value: "SE:sv:Sweden:Swedish", text: "Sweden / Swedish - Svenska" },
        { flag: "🇨🇭", value: "CH:de:Switzerland:German", text: "Switzerland / German - Deutsch" },
        { flag: "🇨🇭", value: "CH:fr:Switzerland:French", text: "Switzerland / French - Français" },
        { flag: "🇨🇭", value: "CH:rm:Switzerland:Romansh", text: "Switzerland / Romansh - Rumantsch" },
        { flag: "🇨🇭", value: "CH:it:Switzerland:Italian", text: "Switzerland / Italian - Italiano" },
        { flag: "🇨🇭", value: "CH:en:Switzerland:English", text: "Switzerland / English" },
        { flag: "🇹🇼", value: "TW:zh:Taiwan:Chinese Traditional", text: "Taiwan / Chinese Traditional (Taiwan) - 中文 繁體" },
        { flag: "🇹🇯", value: "TJ:tg:Tajikistan:Tajik", text: "Tajikistan / Tajik" },
        { flag: "🇹🇯", value: "TJ:ru:Tajikistan:Russian", text: "Tajikistan / Russian - Русский" },
        { flag: "🇹🇿", value: "TZ:en:Tanzania:English", text: "Tanzania / English" },
        { flag: "🇹🇿", value: "TZ:sw:Tanzania:Swahili", text: "Tanzania / Swahili - Kiswahili" },
        { flag: "🇹🇭", value: "TH:en:Thailand:English", text: "Thailand / English" },
        { flag: "🇹🇭", value: "TH:th:Thailand:Thai", text: "Thailand / Thai - ไทย" },
        { flag: "🇹🇱", value: "TL:id:Timor-Leste:Indonesian", text: "Timor-Leste / Indonesian - Bahasa Indonesia" },
        { flag: "🇹🇱", value: "TL:pt:Timor-Leste:Portuguese", text: "Timor-Leste / Portuguese (Portugal) - Português (Portugal)" },
        { flag: "🇹🇱", value: "TL:en:Timor-Leste:English", text: "Timor-Leste / English" },
        { flag: "🇹🇬", value: "TG:fr:Togo:French", text: "Togo / French - Français" },
        { flag: "🇹🇬", value: "TG:ee:Togo:Ewe", text: "Togo / Ewe - Eʋegbe" },
        { flag: "🇹🇰", value: "TK:en:Tokelau:English", text: "Tokelau / English" },
        { flag: "🇹🇴", value: "TO:to:Tonga:Tongan", text: "Tonga / Tongan - Lea Fakatonga" },
        { flag: "🇹🇴", value: "TO:en:Tonga:English", text: "Tonga / English" },
        { flag: "🇹🇹", value: "TT:hi:Trinidad and Tobago:Hindi", text: "Trinidad and Tobago / Hindi - हिंदी" },
        { flag: "🇹🇹", value: "TT:es:Trinidad and Tobago:Spanish", text: "Trinidad and Tobago / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇹🇹", value: "TT:en:Trinidad and Tobago:English", text: "Trinidad and Tobago / English" },
        { flag: "🇹🇹", value: "TT:fr:Trinidad and Tobago:French", text: "Trinidad and Tobago / French - Français" },
        { flag: "🇹🇹", value: "TT:zh:Trinidad and Tobago:Chinese Traditional", text: "Trinidad and Tobago / Chinese Traditional (Taiwan) - 中文 繁體" },
        { flag: "🇹🇳", value: "TN:ar:Tunisia:Arabic", text: "Tunisia / Arabic - العربية" },
        { flag: "🇹🇳", value: "TN:fr:Tunisia:French", text: "Tunisia / French - Français" },
        { flag: "🇹🇷", value: "TR:tr:Turkey:Turkish", text: "Turkey / Turkish - Türkçe" },
        { flag: "🇹🇲", value: "TM:ru:Turkmenistan:Russian", text: "Turkmenistan / Russian - Русский" },
        { flag: "🇹🇲", value: "TM:tk:Turkmenistan:Turkmen", text: "Turkmenistan / Turkmen" },
        { flag: "🇹🇲", value: "TM:uz:Turkmenistan:Uzbek", text: "Turkmenistan / Uzbek - o‘zbek" },
        { flag: "🇺🇸", value: "VI:en:U.S. Virgin Islands:English", text: "U.S. Virgin Islands / English" },
        { flag: "🇺🇬", value: "UG:en:Uganda:English", text: "Uganda / English" },
        { flag: "🇺🇬", value: "UG:sw:Uganda:Swahili", text: "Uganda / Swahili - Kiswahili" },
        { flag: "🇺🇬", value: "UG:ach:Uganda:Acoli", text: "Uganda / Acoli" },
        { flag: "🇺🇬", value: "UG:lg:Uganda:Luganda", text: "Uganda / Luganda" },
        { flag: "🇺🇬", value: "UG:rw:Uganda:Rwanda", text: "Uganda / Rwanda - Ikinyarwanda" },
        { flag: "🇺🇬", value: "UG:nyn:Uganda:Nkore", text: "Uganda / Nkore - Runyankore" },
        { flag: "🇺🇦", value: "UA:uk:Ukraine:Ukrainian", text: "Ukraine / Ukrainian - Українська" },
        { flag: "🇺🇦", value: "UA:ru:Ukraine:Russian", text: "Ukraine / Russian - Русский" },
        { flag: "🇦🇪", value: "AE:ar:United Arab Emirates:Arabic", text: "United Arab Emirates / Arabic - العربية" },
        { flag: "🇦🇪", value: "AE:en:United Arab Emirates:English", text: "United Arab Emirates / English" },
        { flag: "🇦🇪", value: "AE:ur:United Arab Emirates:Urdu", text: "United Arab Emirates / Urdu - اردو" },
        { flag: "🇦🇪", value: "AE:fa:United Arab Emirates:Persian", text: "United Arab Emirates / Persian - فارسی" },
        { flag: "🇦🇪", value: "AE:hi:United Arab Emirates:Hindi", text: "United Arab Emirates / Hindi - हिंदी" },
        { flag: "🇬🇧", value: "GB:en:United Kingdom:English:22", text: "United Kingdom / English" },
        { flag: "🇺🇾", value: "UY:es:Uruguay:Espanol (Latinoamerica):351", text: "Uruguay / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇺🇿", value: "UZ:ru:Uzbekistan:Russian", text: "Uzbekistan / Russian - Русский" },
        { flag: "🇺🇿", value: "UZ:uz:Uzbekistan:Uzbek", text: "Uzbekistan / Uzbek - o‘zbek" },
        { flag: "🇻🇺", value: "VU:fr:Vanuatu:French", text: "Vanuatu / French - Français" },
        { flag: "🇻🇺", value: "VU:en:Vanuatu:English", text: "Vanuatu / English" },
        { flag: "🇻🇪", value: "VE:es:Venezuela:Espanol", text: "Venezuela / Spanish (Latin America) - Español (Latinoamérica)" },
        { flag: "🇻🇳", value: "VN:vi:Vietnam:Vietnamese", text: "Vietnam / Vietnamese - Tiếng Việt" },
        { flag: "🇻🇳", value: "VN:fr:Vietnam:French", text: "Vietnam / French - Français" },
        { flag: "🇻🇳", value: "VN:en:Vietnam:English", text: "Vietnam / English" },
        { flag: "🇻🇳", value: "VN:zh:Vietnam:Chinese Traditional", text: "Vietnam / Chinese Traditional (Taiwan) - 中文 繁體" },
        { flag: "🇿🇲", value: "ZM:en:Zambia:English", text: "Zambia / English" },
        { flag: "🇿🇲", value: "ZM:bem:Zambia:Bemba", text: "Zambia / Bemba - Ichibemba" },
        { flag: "🇿🇲", value: "ZM:loz:Zambia:Lozi", text: "Zambia / Lozi" },
        { flag: "🇿🇲", value: "ZM:ny:Zambia:Chewa", text: "Zambia / Chewa - Nyanja" },
        { flag: "🇿🇲", value: "ZM:tum:Zambia:Tumbuka", text: "Zambia / Tumbuka" },
        { flag: "🇿🇼", value: "ZW:sn:Zimbabwe:Shona", text: "Zimbabwe / Shona - chiShona" },
        { flag: "🇿🇼", value: "ZW:ny:Zimbabwe:Chewa", text: "Zimbabwe / Chewa - Nyanja" },
        { flag: "🇿🇼", value: "ZW:en:Zimbabwe:English", text: "Zimbabwe / English" },
        { flag: "🇿🇼", value: "ZW:zu:Zimbabwe:Zulu", text: "Zimbabwe / Zulu - isiZulu" },
        { flag: "🇿🇼", value: "ZW:tn:Zimbabwe:Tswana", text: "Zimbabwe / Tswana" }
];

export default countries;